### ISSUE TITLE
Best way to synchronize forgejo runner code

### ISSUE THREAD

**Issue by Crown0815** [Crown0815/forgejo-runner-windows#1]
What is the best way to synchronize the code between code.forgejo.org and github? So far I simply do it through my local repo where I have both as a remote. Would it make sense to treat the code at code.forgejo.org as a submodule?

**Comment by earl-warren** [comment]
I think the ideal situation would be if the codebase were the same. I don't think there would be any objection to have windows specific code/documentation in the runner repository at Forgejo, as long as it is clearly stated that it is not supported by Forgejo itself but by this project.

You could make a fork of https://code.forgejo.org/forgejo/runner to https://code.forgejo.org/windows/runner for the sake of proposing pull requests. And mirror this repository here for the sake of tracking issues and support.

Does that sound sensible?

**Comment by Crown0815** [comment]
Thanks @earl-warren. I set everything up the way you suggested.
